"""REVISION_HEADER"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = "4a27fd8a9a66"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_city")),
        sa.UniqueConstraint("name", name=op.f("uq_city_name")),
        sa.CheckConstraint("char_length(name) >= 1", name="check_city_name_non_empty"),
        sa.CheckConstraint(
            "population >= 0", name="check_city_population_non_negative"
        ),
    )
    op.create_table(
        "user",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.CheckConstraint("char_length(name) >= 1", name="check_user_name_non_empty"),
        sa.CheckConstraint(
            "char_length(email) >= 1", name="check_user_email_non_empty"
        ),
    )
    op.create_table(
        "museum",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "city_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name=op.f("fk_museum_city_id_city")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_museum")),
        sa.CheckConstraint(
            "population >= 0", name="check_museum_population_non_negative"
        ),
    )
    op.create_table(
        "visitor_prediction",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column(
            "city_id", advanced_alchemy.types.guid.GUID(length=16), nullable=False
        ),
        sa.Column("predicted_visitors", sa.Integer(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name=op.f("fk_visitor_prediction_city_id_city")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visitor_prediction")),
        sa.CheckConstraint(
            "predicted_visitors >= 0", name="check_predicted_visitors_non_negative"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visitor_prediction")
    op.drop_table("museum")
    op.drop_table("user")
    op.drop_table("city")
    # ### end Alembic commands ###
